FROM node:18-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Expose dev port
EXPOSE 3000

# Run in development mode
CMD ["npm", "run", "dev"]

